import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
import { ReduxProvider } from "./lib/providers/ReduxProvider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <div className="container">
            <div className="header">
              <Link className="link" href="/">Posts</Link>
              <Link className="link" href="/create">Create</Link>
            </div>
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
}
